# Copyright © 2025 The meowg1k Authors
# SPDX-License-Identifier: Apache-2.0

blank_issues_enabled: false
contact_links:
  - name: Ask a Question or Discuss
    url: https://github.com/retran/meowg1k/discussions
    about: Please use GitHub Discussions for questions and general discussions.