services:
  litterbox:
    image: retran/meow-litterbox-go:wip
    container_name: litterbox
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "5222:22"
      - "5201:9001"
    volumes:
      - ..:/home/meow/workspace/
      - ~/.ssh:/home/meow/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
